### ISSUE TITLE
Export md5anim and md5mesh, rendering distortion

### ISSUE THREAD

**Issue by rainyt** [KozGit/Blender-2.8-MD5-import-export-addon#1]
![image](https://user-images.githubusercontent.com/9693090/98226943-a8582500-1f91-11eb-81d9-a3073b823193.png)
![image](https://user-images.githubusercontent.com/9693090/98227007-b60daa80-1f91-11eb-9a08-81bb90c8270c.png)
Is normal md5mesh.
An error occurs when adding md5anim to md5mesh.

**Comment by rainyt** [comment]
@KozGit Can you help me?Thank you!

**Comment by KozGit** [comment]
Does this happen on import/export only?  Can you post the .blend file somewhere?

( edit to import/export )

**Comment by rainyt** [comment]
https://github.com/rainyt/test-assets/blob/master/cattest.blend
Export error happened.
Yes,  this a blender file.

**Comment by KozGit** [comment]
HI, I get a 404 error when I follow that link and cannot download the file.

**Comment by rainyt** [comment]
Sorry, forgot to change private to public. Please try again.

**Comment by KozGit** [comment]
So it looks like there was an issue with the scaling/rotation of your armature.  To fix, try this:

 In object mode, select your armature, then press 'alt-s' to clear the scale.  Next, press 'ctrl-a' and select apply 'rotation and scale'.    The model and animation should now export correctly.  

If you need to re-scale or rotate the model/animation: In object mode, select the mesh and the armature together, then scale and or rotate them together, then press 'ctrl-a' and apply 'rotation and scale' and you should be good.

Let me know if this works!  ( I'm not sure what you're working on, but for what it's worth, .md5 models normally need a root bone named 'origin' to be the parent bone of the armature )

**Comment by rainyt** [comment]
Thanks, this is effective!
