### ISSUE TITLE
Supported versions of blender

### ISSUE THREAD

**Issue by AntonioND** [KozGit/Blender-2.8-MD5-import-export-addon#10]
I've just installed blender 3.3.0, and the plugin seems to work. Is there any reason that makes it incompatible, or is it that you haven't tested it so you haven't updated the documentation?

Thanks for the plugin, by the way!

**Comment by KozGit** [comment]
Hey!  3.1.2 was the newest version of Blender when I last updated the plugin, and I it's simply that I haven't had a chance to test it with the newest versions of blender yet.  Most incompatibilities seem to involve interfacing with the blender UI ( or python version changes ) , so if it's working you are most likely good to go.  Let me know if you run into any issues!

**Comment by AntonioND** [comment]
I think it works pretty well, yeah. So far the only thing I'm missing is trying to understand why all vertices must have non-zero weights, it's the only thing I'm missing to export a model I've created from scratch.

**Comment by KozGit** [comment]
So in the actual .md5mesh file, the vertices don't actually have a position stored, just a weight in reference to a bone.  This is how the final position of the vertex is determined.  If a vertex doesn't have a weight, there is no way for the engine to to calculate it's position.  There are some youtube vids for cleaning up zero weights, I'll see if I can find some links later.

**Comment by AntonioND** [comment]
Ah, I see, thanks. In any case, I've tried to import a MD5 model and export it as it is, and it seems to work fine. I'll be away for a few days, I'll give this a try when I'm back.

**Comment by AntonioND** [comment]
I know you have already closed this, but just to know that yesterday I got back to working on my project, and I managed to export an animated model I created from scratch, using Blender 3.3.0, so it definitely works. :)

EDIT: It took me a while to figure out how Blender works in general, that's why It has taken me this long!

**Comment by AntonioND** [comment]
@KozGit In case you're curious about what I was using this addon for: https://github.com/AntonioND/dsma-library

**Comment by KozGit** [comment]
Hey - that's actually really cool!
