### ISSUE TITLE
Issue with exporting and importing same animation

### ISSUE THREAD

**Issue by pushldr** [KozGit/Blender-2.8-MD5-import-export-addon#11]
I wasn't really sure where else to ask so here I am but I'm having an issue where when I export an animation using your tool then create a new project and import it, the model's bones are offset. 

## Original
![image](https://user-images.githubusercontent.com/55015251/200125130-b780fe16-41c2-4223-b5ab-666f234c1da3.png)

## New Project
![image](https://user-images.githubusercontent.com/55015251/200125168-20dc8b38-940e-4e5c-a5ef-85ba7ca2c45c.png)

Is there something I'm missing here?

**Comment by KozGit** [comment]
Did you make sure all transforms were applied ( ctrl -a, apply all transforms ) before exporting? ( And now I need to see a snowman in one of D3s hell levels :) )

**Comment by pushldr** [comment]
That worked thanks, thanks as well for the awesome tool.  I'm not using it either for D3 ~~although that might be interesting to look into~~. It's just for some personal graphics project :)
