### ISSUE TITLE
Exporting MD5/anim getting 'fixWindings' error.

### ISSUE THREAD

**Issue by darkfader7721** [KozGit/Blender-2.8-MD5-import-export-addon#13]
I'm unsure if this is the place to ask for help.
But I have imported an MD5/animation sequence, and getting an error upon export.
I don't think it's a software issue more than I need help in exporting the md5.

![image](https://user-images.githubusercontent.com/99156325/208316420-fc3c9da3-4f26-4b9a-9e8a-b813176fc740.png)

Any help is greatly appreciated.
thank you.

**Comment by KozGit** [comment]
Hey - which version of blender are you using?  Is there somewhere you could post the blend file?

**Comment by darkfader7721** [comment]
Hey Kozgit,
I appreciate the response. I'm on vacation at the moment and don't have all my files with me.
I am porting the Archvile from Doom3 over to .mdl for a Quake episode that I'm working on, which has both md5/md5animation files associated with it.
I am able to import the md5/md5anim, and i get the error upon export.

I will be back home this weekend, and will dig back into the Blender file, and upload it for viewing.

Thank you, my Friend.

**Comment by darkfader7721** [comment]
Uploaded Archvile blender file here. https://drive.google.com/file/d/1tYxdiLQ2Hbg5iiOlDQob1oGH6CMU7GoB/view?usp=sharing
I have reduced the amount of animations to conform to Quake standards.
I get the above error when trying to export to .mdl

**Comment by KozGit** [comment]
Hey - I apologize for not responding sooner - there was an issue with batch exporting anims that would generate this error - should be fixed now!

**Comment by darkfader7721** [comment]
Thank you, my Friend.
I appreciate the time you have put into this.

The releases say the last release is from Jun 7, 2022, is that one that is updated?

![image](https://user-images.githubusercontent.com/99156325/221029004-e129edda-546c-4156-ab81-63fa73bda677.png)

**Comment by KozGit** [comment]
Whoops  - I updated the code but did not create a release - just published an updated release so you should be good - let me know!

**Comment by KozGit** [comment]
Closing issue - release page updated with version containing fix. Thx!
