### ISSUE TITLE
Bug when exporting anything MD5 (+ image)

### ISSUE THREAD

**Issue by nomnomnomlol** [KozGit/Blender-2.8-MD5-import-export-addon#14]
![image](https://user-images.githubusercontent.com/85874800/210116258-1c60e750-133a-44af-a37a-aae057e1c110.png)
Heres an image of the bug

**Comment by KozGit** [comment]
Can you post the .blend file somewhere? Are all your meshes/models in a collection? ( See readme)

**Comment by KozGit** [comment]
Haven't heard back so this issue will be closed - let me know if you're still having trouble or feel free to open another issue.
