### ISSUE TITLE
Bypass vertex weight

### ISSUE THREAD

**Issue by ryanleethomas** [KozGit/Blender-2.8-MD5-import-export-addon#15]
Is there any way to byspass the vertices and weights? My model does not have any weights set to zero, tested by armature and animation but I am not able to export some of the md5 meshes.
Cheers, and thank you for developing and maintaining this brilliant tool.

**Comment by KozGit** [comment]
Hi! So if the script is reporting a zero weight vertex, then it did find a vertex with 0 weights on it in one of the meshes.  Very often, this is a duplicated vertex, so you may want to remove duplicates ( mesh->clean up->merge by distance ) and then clean weights ( mesh -> weights ->clean.  Set the clean weight limit to something very small like 0.00001 .  If this doesn't work, post a link to your blend somewhere and I'll take a look.

**Comment by KozGit** [comment]
Closing issue, as not really a problem with the exporter - more just how the engine is picky about weights.
