### ISSUE TITLE
All bones defaulting to 5m length during export

### ISSUE THREAD

**Issue by hcet-ti** [KozGit/Blender-2.8-MD5-import-export-addon#16]
## What happened?
I tried to export the mesh and the (unanimated) armature using the "Export Mesh" export option and after importing the same .md5mesh into blender all of the bones' lengths reverted to 5m
![grafik](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/assets/101577739/cfe03946-88a1-434c-a484-15b13f1e4c2d)

## This is the model before the export:
![grafik](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/assets/101577739/e851a93f-7521-4e13-8792-abe06eda5985)
![grafik](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/assets/101577739/38a1e005-7e89-4d06-9ab2-3f8361ead515)
![grafik](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/assets/101577739/672798ea-2428-490a-9dda-24766c3dc2c0)

## This is the model after importing the .md5mesh back into blender:
![grafik](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/assets/101577739/41b0e52e-6956-4aba-80e6-b6ce86fe1b45)
![grafik](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/assets/101577739/82e07c05-5216-406b-a8d0-d59c480712fe)

## Files to reproduce:
[test.zip](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/files/12143664/test.zip)

Btw, I really like your addon, it worked for me before, so I might just be uber-dumb and accidentally turned on some super obvious setting. Anyway, I really hope you can figure this out.

**Comment by KozGit** [comment]
Hi!  So the .md5 format doesn't use or store bone 'length'  - just the position and rotation of each joint.  This is why when you export then re-import a model this happens.  Unfortunately there is no 'fix' for this, as it's a limitation of the file format.

**Comment by hcet-ti** [comment]
Oh, thanks for the response anyways!

**Comment by hcet-ti** [comment]
Oh, thanks for the response anyways!
