### ISSUE TITLE
Split a Blender's mesh by materials

### ISSUE THREAD

**Issue by glKarin** [KozGit/Blender-2.8-MD5-import-export-addon#17]
Thanks for your job first.
I export some other format model file(e.g. gltf2) to Blender, all materials as a single mesh(but convert to obj format and it has more mesh section by assimp). So after export to md5mesh, this file has only a big mesh section with a single shader material, other Blender's materials not used.
I think add a bool option for split a Blender's mesh by materials.
Thanks.

**Comment by KozGit** [comment]
I think because of the way .md5 handles materials, it is better to manually split the model into meshes by material, and then make sure the correct materials are assigned to each mesh before export. I don't see this being a feature I will add, although I will think about it some more.
