### ISSUE TITLE
bug export MD5 animations

### ISSUE THREAD

**Issue by xelodo2024** [KozGit/Blender-2.8-MD5-import-export-addon#18]
export MD5 mesh (ok!!)
![2024-2-27 13-29-45](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/assets/151673007/3c15796d-679e-4c0a-ad8a-e10257f53ec9)
export MD5 animation: 
![2024-2-27 13-33-58](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/assets/151673007/11ead86b-deff-4bb8-be41-c8f6dcba67d7)
![2024-2-27 14-1-36](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/assets/151673007/b7b19450-e5dd-4dfe-ad38-be5e4bdf765e)
Model original:
[Armature_original.zip](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/files/14419673/Armature_original.zip)
Model export MD5:
[Armature_original.zip](https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/files/14419696/Armature_original.zip)

**Comment by KozGit** [comment]
Hi - did you apply all transforms ( loc, rot, scale ) prior to export? That's a common cause for this type of problem. Thx

**Comment by KozGit** [comment]
Closing issue, as no response.  If issue still persists, feel free to re-open. Thx
