### ISSUE TITLE
Please specify license as MIT

### ISSUE THREAD

**Issue by kattkieru** [KozGit/Blender-2.8-MD5-import-export-addon#19]
Hi there,

Would you mind specifying the license in this repo? I'd prefer MIT / Apache 2 / BSD.

Thanks!

**Comment by KozGit** [comment]
This code is based on an older blender plugin by nemyax found here: https://sourceforge.net/p/blenderbitsbobs/wiki/MD5%20exporter/

I can't find any license for this, so am hesitant to assign one without approval from the original author.  There are other versions of this exporter around, some of which have the MIT license assigned if that is important to you.
