### ISSUE TITLE
cannot import md5mesh into blender 2.93.1

### ISSUE THREAD

**Issue by ThronedSeal2094** [KozGit/Blender-2.8-MD5-import-export-addon#3]
When trying to import an md5mesh I get a traceback call error in line 1003 saying "TypeError: float() argument must be a string or a number, not '_PropertyDeferred'" any suggestions as to why this may be happening.

**Comment by KozGit** [comment]
Hey, does this happen with any mesh or just a specific one? 

I haven't actually tested with blender 2.93.1 yet - I may have to look at this.

**Comment by KozGit** [comment]
So this is definitely due to changes in the blender 2.93 API.  Nothing huge,  just the way properties for the windows need to be defined.  Hopefully I can update tomorrow.

**Comment by ThronedSeal2094** [comment]
I did try the addon on blender 2.8 but the mesh I imported ended up looking squashed. Maybe another issue to look into also.

**Comment by KozGit** [comment]
Can you post a link to that mesh?  If it's a valid .md5mesh there shouldn't be any deforms on import.

**Comment by ThronedSeal2094** [comment]
Here is a copy of the md5mesh and the md5anim files that I would like to use the addon for (https://drive.google.com/drive/folders/1QyeutISI9IPiyL-B25aTFK_KyBg89MIA?usp=sharing). This is what it should look like minus the texture of course.
![Capture](https://user-images.githubusercontent.com/86875146/128632215-efae6df9-8293-457d-887e-6eb846d98bd6.JPG)

**Comment by KozGit** [comment]
Where did that .md5 come from?  It doesn't import correctly with any verison of a .md5 viewer or importer I can find.  ( All the way back to blender 2.49, and none of the .md5 model viewers I have )

**Comment by ThronedSeal2094** [comment]
The files came from a utility called BRRES Viewer. It is used for ripping models, textures, and animations from a WII .iso. I have uploaded the program and the .brres file to the google drive link used earlier. Hopefully this may help you to determine where the issue may lie. I suspect that the program may use a very old version of the md5 file system, but your guess is as good as mine.

**Comment by KozGit** [comment]
That converter did not correctly create a .md5 mesh.  I don't really have time to troubleshoot a different utility, so my recommendation is to try to convert the model and animation into something blender will recognize, then use this ( or a different ) .md5 import/export plugin to create your .md5 models and anims.  This will most likely require some manual work on the model - if you're not already familiar with the format you may want to look at some md5 tutorials online.

**Comment by ThronedSeal2094** [comment]
Thanks for trying, I guess I'd better do some more research into this myself.

**Comment by xDShot** [comment]
Any progress?

**Comment by Stefano-Panzeri** [comment]
> 
> 
> So this is definitely due to changes in the blender 2.93 API. Nothing huge, just the way properties for the windows need to be defined. Hopefully I can update tomorrow.

If you want, take a look at my pull request, it makes the plugin work on 2.93
#5

**Comment by katastic** [comment]
I'm trying to load a quake 1 model (from the remaster but it should be stock) and I'm getting the same problem. It appears that the "operator presets" configuration settings do not show up in the importer dialog, so they're not defined. 

The menu is depicted here:
https://youtu.be/xocPffM_x5Y?t=25

At which point, they're left undefined and the python throws an exception.

I'll try that pull request next

````Python
Python: Traceback (most recent call last):
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_md5_28.py", line 1003, in execute
    rotdeg = float(self.reorientDegrees)
TypeError: float() argument must be a string or a number, not '_PropertyDeferred'

location: <unknown location>:-1


````

**Comment by katastic** [comment]
@Stefano-Panzeri WORKS GREAT! Thank you!

**Comment by KozGit** [comment]
The script has been updated to support thru Blender 3.1.2 - please let me know if you have any additional issues.
