### ISSUE TITLE
Activating the Addon in Blender 2.83.6 (LTS) Throws Error

### ISSUE THREAD

**Issue by Jaws-git** [KozGit/Blender-2.8-MD5-import-export-addon#4]
Here's a screenshot of the error in question when clicking the checkbox to activate the plugin.

![image](https://user-images.githubusercontent.com/22118709/128832916-ae005ed0-5790-4155-9bb4-2b05bbe6de1a.png)

Curiously the addon also prompts you to update to 2.8x. This is Blender 2.83 LTS.

![image](https://user-images.githubusercontent.com/22118709/128832833-69cf17a2-5db7-405c-97bb-1083e7e73873.png)

**Comment by CrazyHairGuy** [comment]
I can activate it (in Blender 2.93.2)

![image](https://user-images.githubusercontent.com/9155262/130271293-974810b6-ade0-4cc2-a114-3908856d2c9d.png)

but upon importing a model, it throws an error:

![image](https://user-images.githubusercontent.com/9155262/130271470-f94a64be-dcf4-457f-9780-8e0b85553cdc.png)

**Comment by KozGit** [comment]
The script has been updated to support thru blender 3.1.2 - please let me know if you are still having issues.
