### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by DMJC** [KozGit/Blender-2.8-MD5-import-export-addon#7]
Please give this project a license as I would like to distribute the plugin with an Apache 2.0 licensed game. Linwarrior https://github.com/DMJC/linwarrior

**Comment by KozGit** [comment]
This is based on the plugin originally written by nemyax.  The only thing even resembling a license I could find regarding that plugin was the statement 'Python scripts for personal use in Blender', so I am uncomfortable assigning any specific license.  I have no issue with my changes to the plugin being distributed, but I can't speak for the original author.
