### ISSUE TITLE
unresolved merge in io_scene_md5_28.py

### ISSUE THREAD

**Issue by joel-bluedata** [KozGit/Blender-2.8-MD5-import-export-addon#8]
Cf. the section starting `<<<<<<< HEAD` : https://github.com/KozGit/Blender-2.8-MD5-import-export-addon/blob/35fdb03d09ab712179cfd4b676ae9986314c38bb/io_scene_md5_28.py#L1654

**Comment by KozGit** [comment]
Should be fixed now! Thanks for the heads up.
